name: publish_article

on:
  repository_dispatch:
    types: [publish_article]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: install modules
        run: npm install

      - name: export next
        run: npm run export
        env:
          API_KEY: ${{ secrets.API_KEY }}
          ENDPOINT: ${{ secrets.ENDPOINT }}

      - name: ftp deploy action
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          LOCAL_DIR: ./
          REMOTE_DIR: ""
