name: publish_article

on:
  repository_dispatch:
    types: [publish_article]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install Modules
        run: npm install

      - name: Export File
        run: npm run export
        env:
          API_KEY: ${{ secrets.API_KEY }}
          ENDPOINT: ${{ secrets.ENDPOINT }}

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/
          server-dir: ./www/
